name       : dhclient
version    : 4.4.2_p1
release    : 8
source     :
    - https://ftp.isc.org/isc/dhcp/4.4.2-P1/dhcp-4.4.2-P1.tar.gz : b05e04337539545a8faa0d6ac518defc61a07e5aec66a857f455e7f218c85a1a
license    : MPL-2.0
component  : network.base
summary    : ISC DHCP client
description: |
    ISC DHCP client
rundeps    :
    - iproute2
setup      : |
    %patch -p1 < $pkgfiles/0001-Point-dhclient-script-path-to-where-it-s-installed.patch
    %patch -p1 < $pkgfiles/0002-117-fixed-gcc-10-compilation-issues.patch
    %configure --sbindir=/usr/bin \
               --with-srv-lease-file=/var/lib/dhcpd/dhcpd.leases       \
               --with-srv6-lease-file=/var/lib/dhcpd/dhcpd6.leases     \
               --with-cli-lease-file=/var/lib/dhclient/dhclient.leases \
               --with-cli6-lease-file=/var/lib/dhclient/dhclient6.leases
build      : |
    %make -j1
install    : |
    %make_install -C client
    install -d $installdir/var/lib/dhclient
    mkdir -p $installdir/usr/share/dhclient && mv $installdir/etc/dhclient.conf.example $installdir/usr/share/dhclient/.
    install -m 00755 client/scripts/linux $installdir/usr/bin/dhclient-script
    rmdir $installdir/etc
