name       : dhclient
version    : 4.4.1
release    : 6
source     :
    - ftp://ftp.isc.org/isc/dhcp/4.4.1/dhcp-4.4.1.tar.gz : 2a22508922ab367b4af4664a0472dc220cc9603482cf3c16d9aff14f3a76b608
license    : ISC
component  : network.base
summary    : ISC DHCP client
description: |
    ISC DHCP client
rundeps    :
    - iproute2
setup      : |
    %patch -p1 < $pkgfiles/0001-Point-dhclient-script-path-to-where-it-s-installed.patch
    %configure --sbindir=/usr/bin \
               --with-srv-lease-file=/var/lib/dhcpd/dhcpd.leases       \
               --with-srv6-lease-file=/var/lib/dhcpd/dhcpd6.leases     \
               --with-cli-lease-file=/var/lib/dhclient/dhclient.leases \
               --with-cli6-lease-file=/var/lib/dhclient/dhclient6.leases
build      : |
    %make -j1
install    : |
    %make_install -C client
    install -d $installdir/var/lib/dhclient
    mkdir -p $installdir/usr/share/dhclient && mv $installdir/etc/dhclient.conf.example $installdir/usr/share/dhclient/.
    install -m 00755 client/scripts/linux $installdir/usr/bin/dhclient-script
    rmdir $installdir/etc
